### ISSUE TITLE
Problem importing uxs on MacOS

### ISSUE THREAD

**Issue by peedrr** [binares/uxs#2]
I'm trying to work with uxs on MacOS but I fell at the first hurdle!

`import uxs`
Results in:
```
ModuleNotFoundError: No module named 'AppKit'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7527588d0428> in <module>
----> 1 import uxs
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/uxs/__init__.py in <module>
      5 import yaml
      6 
----> 7 from uxs.base.socket import (ExchangeSocket, ExchangeSocketError)
      8 
      9 from uxs.base.ccxt import (get_name, get_exchange, get_sn_exchange, init_exchange,
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/uxs/base/socket/__init__.py in <module>
----> 1 from .exchange import ExchangeSocket
      2 from .errors import (ExchangeSocketError, ConnectionLimit)
      3 from .orderbook import OrderbookMaintainer
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/uxs/base/socket/exchange.py in <module>
     10 td = datetime.timedelta
     11 
---> 12 from ..auth import get_auth2, EXTRA_TOKEN_KEYWORDS
     13 from ..ccxt import init_exchange, _ccxtWrapper
     14 from .. import poll
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/uxs/base/auth.py in <module>
      7 dt = datetime.datetime
      8 
----> 9 from ._settings import get_setting, set as _set
     10 
     11 from fons.crypto import password_encrypt, password_decrypt
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/uxs/base/_settings.py in <module>
     22 }
     23 
---> 24 APPDATA_DIR = get_appdata_dir('uxs-python', make=True)
     25 SETTINGS_PATH = os.path.join(APPDATA_DIR, 'settings.yaml')
     26 SETTINGS = {
~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/fons/os.py in get_appdata_dir(appname, windows_select, make)
    158 
    159     if _PLATFORM == 'Darwin':
--> 160         from AppKit import NSSearchPathForDirectoriesInDomains
    161         # http://developer.apple.com/DOCUMENTATION/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Functions/Reference/reference.html#//apple_ref/c/func/NSSearchPathForDirectoriesInDomains
    162         # NSApplicationSupportDirectory = 14
ModuleNotFoundError: No module named 'AppKit'
```

Obviously attempted to install [AppKit](https://pypi.org/project/AppKit/) but the listing on PyPI was last updated 2014 and the GitHub project page no longer exists. This didn't work

An answer StackOverflow suggested installing [PyObjC](https://pypi.org/project/pyobjc/). Initially this didn't work, then a subsequent Google search revealed that the `NSSearchPathForDirectoriesInDomains` method is in the `Foundation` module (which presumably got imported with `PyObjC`). 

I finally managed to `import uxs` by editing line 160 of the file `~/.pyenv/versions/3.9.4/lib/python3.9/site-packages/fons/os.py` (see above traceback) to read `from Foundation import NSSearchPathForDirectoriesInDomains`

I'm completely new to Python so I'm afraid I don't know enough to understand who takes ownership of the above os.py file and whether my issue needs to bubble up to a different project!

**Comment by binares** [comment]
Sorry for the delayed response. The truth is I haven't tested it on mac, as I don't own one nor can properly emulate it.

`os.path.expanduser('~/Library/Application Support/')`

Can you tell me if the above gives the same result as

`NSSearchPathForDirectoriesInDomains(14, 1, True)[0]`

If so, I would drop the AppKit/PyObj dependency completely (yes, I maintain `fons` library)

**Comment by binares** [comment]
@peedrr  Gonna go with `os.path.expanduser('~/Library/Application Support/')`

**Comment by binares** [comment]
Solved in fons new version `pip install --upgrade fons`
